dataset_name: cmapps_fd003
paths:
  raw_train_file: /path/to/train_FD003.txt
  raw_test_file: /mnt/data/test_FD003.txt
  raw_rul_file: /mnt/data/RUL_FD003.txt
  clean_output_path: data/clean/cmapss/fd003_clean.parquet
  features_output_path: data/features/cmapss/fd003_features.parquet
schema:
  column_map:
    unit: unit
    cycle: cycle
    setting1: setting1
    setting2: setting2
    setting3: setting3
    s1: s1
    s2: s2
    s3: s3
    s4: s4
    s5: s5
    s6: s6
    s7: s7
    s8: s8
    s9: s9
    s10: s10
    s11: s11
    s12: s12
    s13: s13
    s14: s14
    s15: s15
    s16: s16
    s17: s17
    s18: s18
    s19: s19
    s20: s20
    s21: s21
  target_col: rul
  drop_features: []
  categorical_features: []
  numeric_features:
  - setting1
  - setting2
  - setting3
  - s1
  - s2
  - s3
  - s4
  - s5
  - s6
  - s7
  - s8
  - s9
  - s10
  - s11
  - s12
  - s13
  - s14
  - s15
  - s16
  - s17
  - s18
  - s19
  - s20
  - s21
prep:
  drop_na: false
  impute: median
  scale: standard
  use_windowing: true
  window_params:
    window_size: 30
    step_size: 1
    label_at_end: true
    cap_rul: 125
  derive_rul:
    use_cap: true
    cap_value: 125
split:
  method: by_unit_holdout
  val_units_ratio: 0.1
  random_state: 42
  group_by: unit
file_format:
  delimiter: \\s+
  header: false
  columns_in_order:
  - unit
  - cycle
  - setting1
  - setting2
  - setting3
  - s1
  - s2
  - s3
  - s4
  - s5
  - s6
  - s7
  - s8
  - s9
  - s10
  - s11
  - s12
  - s13
  - s14
  - s15
  - s16
  - s17
  - s18
  - s19
  - s20
  - s21
